name: Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, edited]

permissions:
  pull-requests: write
  contents: read

jobs:
  add_reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kentaro-m/auto-assign-action@v1.2.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            NaralaJithendra
      - name: Log Reviewer Assignment
        run: echo "Reviewers assigned successfully!"
